### ISSUE TITLE
Questions of the tables in your paper

### ISSUE THREAD

**Issue by ghost** [LiheYoung/ST-PlusPlus#1]
Hi,

I'm a beginner of the semi-supervised segmentation, and I'm actually very confused of the settings that the recent paper use. For example, in you Table 1,
![image](https://user-images.githubusercontent.com/33716428/124046906-25b93400-da52-11eb-9fa5-3e1350134fac.png)

For each percentage of the annotated labels, larger number of labels yields better result which is totally make sense. However, in your Table 2,
![image](https://user-images.githubusercontent.com/33716428/124046991-55683c00-da52-11eb-91e1-dfb326e1c54f.png)

With only 1464 original annotated images you reach even higher result by compared with the $2645$ images in Table 1. Could I kindly ask what caused this difference?

Cheers,

**Comment by LiheYoung** [comment]
Hi, thanks for noticing it and raising the question.

Generally speaking, the annotations of labeled images in Table.1 and Table.2 are of different qualities.

Specifically, the Pascal VOC 2012 training set originally contains 1,464 high-quality annotations. Later it is augmented by extra 9,118 lower-quality annotations from the SBD dataset to form 10,582 image-masks pairs. 

The labeled images in Table.1 are randomly selected from the augmented training set with 10,582 imaages in total, while the labeled images in Table.2 are selected from the high-quality original training set with 1,464 images in total. Please refer to the first sentence of the table caption for difference. By the way, the unlabeled images are both the remaining images in the augmented training set.

The settings of Table.1 follow the mainstream practice in recent works like [Context-aware Consistency](https://jiaya.me/papers/semiseg_cvpr21.pdf) , while Table.2 follows the state-of-the-art method [PseudoSeg](https://arxiv.org/abs/2010.09713).

**Comment by ghost** [comment]
That's clarify a lot. 
Thanks very much!

**Comment by geek-APTX4869** [comment]
The experiments in Table 1 were performed on which division of Pascal VOC？
