### ISSUE TITLE
Question about the reported results

### ISSUE THREAD

**Issue by 4-0-4-notfound** [LiheYoung/ST-PlusPlus#10]
Although this work is very insightful, I have some questions about the report results. After running the code for several times, I found that the biggest gap in baseline（Stage 1）is 0.47 of mIoU. This value is even greater than the ST++'s improvement over ST in some data splits. So what is your principle for those reported results?

![image](https://user-images.githubusercontent.com/76674846/135016284-0e06b37c-747b-4a5a-8f6b-644352cd0daf.png)

**Comment by LiheYoung** [comment]
Hi,

You provide the two results under the setting of 92 labeled images, where the improvement of our ST++ over ST is 3.9% ( 65.2% vs 61.3%), which is a much larger margin than 0.47.

As you point out, the performance gain of our ST++ over ST is less obvious in several settings. You may try other networks (e.g., DeepLabv3+) or settings. Generally speaking, more labeled images, less obvious improvement.

For a stable evaluation, you can even run ST++ and ST on all three data splits under each setting. Limited by time, we only run the first data split several times under certain settings to make sure stability.

**Comment by 4-0-4-notfound** [comment]
However, in more labeled images setting like 732 labeled images in VOC 2012, the gap is even more unignorable comparing to ST++‘s improvement over ST.

<img width="546" alt="b441e304-eae2-4adc-87d0-2e0cbe34cbc1" src="https://user-images.githubusercontent.com/76674846/135027330-949163c5-1e7c-4fc6-848b-59b758af2812.png">

Furthermore, in 1464 labeled images setting, ST++'s performance is even worse than ST occasionally.
<img width="159" alt="2499c9e8-65c1-44bb-97f0-60cab490f0b1" src="https://user-images.githubusercontent.com/76674846/135027353-5173096e-01fb-462d-9836-e5779f6b02eb.png">

**Comment by LiheYoung** [comment]
In the label-scarce setting, when you merely leverage the labeled images, the performance variance can be large. However, when incorporating abundant unlabeled images, the performance will be more stable and harder to improve. So I don't think it is fair or necessary to compare the variance of SupOnly results with the gain of our ST++ over ST.

As for your 1464 results, you may run multiple times and report the average. I want to point out that our ST already surpasses the fully-supervised performance, so the gain of our ST++ is less obvious. But I do observe consistent improvements in my experiments.
