### ISSUE TITLE
你好作者！我想请问一下，这个开源代码的pytorch版本是多少？

### ISSUE THREAD

**Issue by yang654123** [LiheYoung/ST-PlusPlus#14]

**Comment by LiheYoung** [comment]
你好，我们在PyTorch1.3和1.6上都做过实验，应该都可以。

**Comment by yang654123** [comment]
作者你好，我在运行代码的时候出现了一个问题，在imageDraw.py这个文档里出现了
File "D:\anaconda3.5\envs\torch1.6\lib\site-packages\PIL\ImageDraw.py", line 259, in rectangle
    self.draw.draw_rectangle(xy, ink,0, width)

TypeError: an integer is required (got type tuple)
出现了这个问题。我在百度上查询的Torch的版本问题，我觉得也可能是draw.draw_rectangle函数传入类型的问题。
很感激期待您的回复。

**Comment by yang654123** [comment]
我用的是Torch=1.6

**Comment by LiheYoung** [comment]
你可以看一下是在ST++哪一行报的错，另外也有可能是Pillow的版本问题，我用的是Pillow8.3.1

**Comment by yang654123** [comment]
> 

我试了一下回退到pillow8.3.1还是会报错

**Comment by LiheYoung** [comment]
麻烦截一下完整的报错信息

**Comment by yang654123** [comment]
![image](https://user-images.githubusercontent.com/64208861/165229251-f9e7acab-a3dd-4ad5-8cb2-655b0d88963b.png)

$ python -W ignore main.py --dataset pascal --data-root E:/Yang/ST-PlusPlus/Pascal/VOCdevkit/VOC2012 --batch-size 16 --backbone resnet50 --model deeplabv3p
lus --labeled-id-path dataset/splits/pascal/1_8/split_0/labeled.txt --unlabeled-id-path dataset/splits/pascal/1_8/split_0/unlabeled.txt --pseudo-mask-path 
outdir/pseudo_masks/pascal/1_8/split_0 --save-path outdir/models/pascal/1_8/split_0

Namespace(backbone='resnet50', batch_size=16, crop_size=321, data_root='E:/Yang/ST-PlusPlus/Pascal/VOCdevkit/VOC2012', dataset='pascal', epochs=80, labeled
_id_path='dataset/splits/pascal/1_8/split_0/labeled.txt', lr=0.001, model='deeplabv3plus', plus=False, pseudo_mask_path='outdir/pseudo_masks/pascal/1_8/spl
it_0', reliable_id_path=None, save_path='outdir/models/pascal/1_8/split_0', unlabeled_id_path='dataset/splits/pascal/1_8/split_0/unlabeled.txt')

================> Total stage 1/3: Supervised training on labeled images (SupOnly)

    draw.rectangle((0, 0, width - 1, height - 1), outline=color, width=border)
  File "D:\anaconda3.5\envs\torch1.6\lib\site-packages\PIL\ImageDraw.py", line 259, in rectangle
    self.draw.draw_rectangle(xy, ink, 0, width)
TypeError: an integer is required (got type tuple)

**Comment by yang654123** [comment]
> 麻烦截一下完整的报错信息

$ python -W ignore main.py --dataset pascal --data-root E:/Yang/ST-PlusPlus/Pascal/VOCdevkit/VOC2012 --batch-size 16 --backbone resnet50 --model deeplabv3p
lus --labeled-id-path dataset/splits/pascal/1_8/split_0/labeled.txt --unlabeled-id-path dataset/splits/pascal/1_8/split_0/unlabeled.txt --pseudo-mask-path 
outdir/pseudo_masks/pascal/1_8/split_0 --save-path outdir/models/pascal/1_8/split_0

Namespace(backbone='resnet50', batch_size=16, crop_size=321, data_root='E:/Yang/ST-PlusPlus/Pascal/VOCdevkit/VOC2012', dataset='pascal', epochs=80, labeled
_id_path='dataset/splits/pascal/1_8/split_0/labeled.txt', lr=0.001, model='deeplabv3plus', plus=False, pseudo_mask_path='outdir/pseudo_masks/pascal/1_8/spl
it_0', reliable_id_path=None, save_path='outdir/models/pascal/1_8/split_0', unlabeled_id_path='dataset/splits/pascal/1_8/split_0/unlabeled.txt')

================> Total stage 1/3: Supervised training on labeled images (SupOnly)

    draw.rectangle((0, 0, width - 1, height - 1), outline=color, width=border)
  File "D:\anaconda3.5\envs\torch1.6\lib\site-packages\PIL\ImageDraw.py", line 259, in rectangle
    self.draw.draw_rectangle(xy, ink, 0, width)
TypeError: an integer is required (got type tuple)

**Comment by LiheYoung** [comment]
这边只能看到在PIL库内报了错，是对应``semi.py``或``transform.py``里的哪一行呢？有点奇怪，我这边没遇到过类似的报错。

**Comment by yang654123** [comment]
> 

那您方便么，可以帮忙帮我看一下么，目前还是这个错误，我的微信是15142235012，QQ是3049365901   您能一直解答我的问题我已经很开心了

**Comment by LiheYoung** [comment]
没关系，微信已加。

**Comment by woaicv** [comment]
> 没关系，微信已加。
作者您好，我也遇到了这个错误不知道怎么解决。希望您能解答一下，万分感谢🙏
