### ISSUE TITLE
Pretrained CityScapes and Pascal Model weights

### ISSUE THREAD

**Issue by aneesh3108** [LiheYoung/ST-PlusPlus#17]
Hello, 

I am wondering if it would be possible for you to share the final model weights (and training logs) on either of the CityScapes and Pascal splits? 

I have some class-wise comparisons and visualizations to perform, and I am unable to do them at this point. 

Thank you.

**Comment by LiheYoung** [comment]
We have found and uploaded two fully trained weights of our ST method under settings of [183](https://drive.google.com/file/d/1h1go8MFJin3_bFz_Ag-a6XoFjvYB5Th4/view?usp=sharing) and [732](https://drive.google.com/file/d/1Uehk-EmZ1qWc1JyAxBItjsNJZnibVVVI/view?usp=sharing) labeled data respectively on the Pascal. The performance under ``183 labeled data`` is ``68.02`` (paper: ``68.2``), while the one under ``732 labeled data`` is ``76.99`` (paper: ``76.3``).

**Comment by aneesh3108** [comment]
Thank you
