### ISSUE TITLE
关于cutout

### ISSUE THREAD

**Issue by Renp1ngs** [LiheYoung/ST-PlusPlus#19]
感谢您精彩的工作。我有以下几个问题，希望可以得到您的解答。
1. 是否可以解释一下代码中cutout的实现呢？这两个变量分别代表什么意思呢？
> erase_w = int(np.sqrt(size / ratio))
> erase_h = int(np.sqrt(size * ratio))

2. 请问是否有尝试过用cutmix代替cutout的实验呢？

**Comment by LiheYoung** [comment]
我们主要参考了[这里](https://github.com/yu4u/cutout-random-erasing/blob/master/random_eraser.py)Cutout的实现，``ratio``能够控制Cutout区域长宽的比例，``size``是Cutout的面积，``erase_h``和``erase_w``分别是Cutout区域的高度和宽度；

我们有尝试过CutMix，会更好一些。

**Comment by Renp1ngs** [comment]
感谢您的回复。
