### ISSUE TITLE
about training detail

### ISSUE THREAD

**Issue by wsl-Git-Hub** [LiheYoung/ST-PlusPlus#21]
![image](https://user-images.githubusercontent.com/70445168/188899356-f4b906d6-deb7-4dab-9cc8-c206e1663337.png)
Hello, I have a confusion hope can be helped, why when `mode== label`, and can get the mask of unlabeled.

**Comment by LiheYoung** [comment]
Hi,

Do you mean why we are allowed to obtain the groundtruth mask of unlabeled images? If so, actually we do not use these masks for training, but for measuring the quality of our produced pseudo masks.

You may check [here](https://github.com/LiheYoung/ST-PlusPlus/blob/f4ff2ebaae15fb3e2c6000b50d62a67e40058118/main.py#L310) for details.

**Comment by wsl-Git-Hub** [comment]
Thank you for your answer. I know the ground truth doesn't use training, and I wonder whether obtaining the ground truth of unlabeled data in the semi-supervised task is correct. Thanks again

**Comment by LiheYoung** [comment]
As long as you do not use these groundtruth masks for training, it is certainly okay.

**Comment by wsl-Git-Hub** [comment]
ok！thanks
