### ISSUE TITLE
Supervised training

### ISSUE THREAD

**Issue by ltb801** [LiheYoung/ST-PlusPlus#23]
Hello, thank you very much for your work!

I'd like to ask what is the purpose of doubling the training ids when the number of labeled images is less than 200?

![image](https://user-images.githubusercontent.com/70506111/193958428-598438cf-680f-4338-8da5-3998c7183302.png)

**Comment by LiheYoung** [comment]
Hi, I just want to train it for more iterations when images are limited. You can also double the epochs.

**Comment by ltb801** [comment]
If I'm understanding it correctly, does that mean the training images will be duplicated?

**Comment by LiheYoung** [comment]
Yes.

**Comment by ltb801** [comment]
Thank you for your quick response.
