### ISSUE TITLE
pseudo- labels生成之后，更新labelled data的问题

### ISSUE THREAD

**Issue by XiaoyanQian** [LiheYoung/ST-PlusPlus#24]
你好，谢谢你的工作。我有个小问题，请问pseudo- labels生成，是实时就加入 原来的labelled data里面，保持一直的训练模式，还是人为地需要把生成的pseudo- labels 放入原来的labelled data，再开始重新训练模型。

那如果是人为地加入pseudo-labels, 是不是就应该可以理解成分阶段循环训练模型。ô
请问是不是有end-to-end, 就是pseudo-labels generating 和 re-train模型合并的，就不分阶段，实时地进行生成伪标签和重新训练模型

**Comment by LiheYoung** [comment]
你好，我们的这个框架不是实时的加入伪标签，而是分阶段的；关于end-to-end实时利用伪标签的框架，可以参考我们最新的工作UniMatch [[Paper](https://arxiv.org/abs/2208.09910), [Code](https://github.com/LiheYoung/UniMatch)]。

**Comment by XiaoyanQian** [comment]
谢谢你哈
