### ISSUE TITLE
  作者你好，我想问一下unlable.txt的文件怎么来的。unlable的标签不应该是没有的吗？

### ISSUE THREAD

**Issue by lgchencong** [LiheYoung/ST-PlusPlus#26]
作者你好，我想问一下unlable.txt的文件怎么来的。unlable的标签不应该是没有的吗？

**Comment by LiheYoung** [comment]
你好，数据集中其实也是包含无标签图像的标注的，不过unlabeled.txt里面的标签路径中的标签我们并没有用来训练

**Comment by lgchencong** [comment]
谢谢作者的回复

**Comment by ZeroAC** [comment]
作者您好，请问一下，为啥监督训练数据的数据原图和语义分割的结果会左右颠倒

**Comment by LiheYoung** [comment]
@ZeroAC 你好，这具体是指什么问题呢，原图和分割结果似乎并不存在左右颠倒的问题。
