### ISSUE TITLE
有关于灰度图像

### ISSUE THREAD

**Issue by caichy233** [LiheYoung/ST-PlusPlus#28]
你好，我想用这个模型训练灰度图像，请问可以实现吗

**Comment by LiheYoung** [comment]
你好，是可以的，按理来说只需要修改一下``semi.py``中受图像维度改变影响的部分，以及将模型的输入改成单通道的，不过那样会导致ImageNet预训练模型无法正确加载；或者更方便的方式是以RGB的方式去读取这个灰度图像，作为三通道的输入。
