### ISSUE TITLE
About the `evaluation bug' 

### ISSUE THREAD

**Issue by Haochen-Wang409** [LiheYoung/ST-PlusPlus#3]
Hi, I'm a beginner in semantic segmentation, and thanks for your great work. It seems ST++ is the only method which select `reliable DT mask' for unlabeled images.

I'm interested in the `evaluation bug' metioned on Table.1
![image](https://user-images.githubusercontent.com/62472073/130573021-700ed826-2452-4315-8fd0-e703554c6594.png)
Could you give me a brief introduction about it?

**Comment by LiheYoung** [comment]
Hi Haochen, thank you for your interest in our work.

The evaluation bug is reported by the authors of GCT. Briefly speaking, in the GCT original implementation and reported performance, the authors did a ``CenterCrop`` operation on testing images during inference which indeed shouldn't be conducted. The right practice is to predict and evaluate each testing image on its original resolution. 

You may refer to the second *Note* at [this link](https://github.com/ZHKKKe/PixelSSL/tree/master/task/sseg) for more details.

**Comment by Haochen-Wang409** [comment]
Thanks for your explaination!
If we must evaluate each testing image on the original shape, the batch size have to be 1 when validate. Am I right?

**Comment by LiheYoung** [comment]
Yes, you are right! :)

**Comment by Haochen-Wang409** [comment]
Thanks a lot!

**Comment by pascal1129** [comment]
I found `CenterCrop` was uesd in [Semi-Supervised Semantic Segmentation with Cross Pseudo Supervision](https://openaccess.thecvf.com/content/CVPR2021/papers/Chen_Semi-Supervised_Semantic_Segmentation_With_Cross_Pseudo_Supervision_CVPR_2021_paper.pdf) and [Pixel Contrastive-Consistent Semi-Supervised Semantic Segmentation](https://arxiv.org/pdf/2108.09025.pdf), which was published in CVPR 2021 and ICCV 2021 respectively. So i am quite confused about whether to use `CenterCrop` in evaluation.

**Comment by LiheYoung** [comment]
From my perspective, it is more practical to evaluate on original resolution in semantic segmentation.
