### ISSUE TITLE
Using the best model to do pseudo labeling

### ISSUE THREAD

**Issue by geocccc** [LiheYoung/ST-PlusPlus#30]
Hi thanks for your work.

I noticed that you use the best checkpoint to do the pseudo labeling

https://github.com/LiheYoung/ST-PlusPlus/blob/561d68fdd452b6764cccabac1472e43f23366078/main.py#L129

The best model is selected by the evaluation on the val set with ground truth label. Do you think this cause an information leaking?

Although the ground truth doesn’t explicitly involve in the training. it does provide some information for the model checkpoint selection.

When we train our model, we should make sure that we can touch nothing about the val set.

Have you tried to train your method without this selection? Say just use the final checkpoint?

thanks.

**Comment by LiheYoung** [comment]
Thank you for mentioning it. Honestly, I currently think it is more convincing to use the final checkpoint for pseudo labeling. We previously use the best checkpoint, but not intentionally. And as discussed in https://github.com/LiheYoung/ST-PlusPlus/issues/7, the performance of the final epoch is comparable to the best model during training. You can simply use the final model for evaluation.

**Comment by geocccc** [comment]
Thanks.
