### ISSUE TITLE
最终的IOU

### ISSUE THREAD

**Issue by Yan1026** [LiheYoung/ST-PlusPlus#31]
请问最终的IOU就是最后一轮最后一张图片的mIOU吗？还是最后一轮的平均IOU？是我操作的不对吗，最后的输出只到这了

mIOU: 74.82: 100%|██████████| 1449/1449 [01:13<00:00, 19.79it/s]
mIOU: 74.82: 100%|██████████| 1449/1449 [01:13<00:00, 19.77it/s]

**Comment by LiheYoung** [comment]
你好，这里显示的mIoU就是整个验证集的mIoU，并不是最后一张图片的。

**Comment by Yan1026** [comment]
感谢您的回答！

**Comment by yyamx** [comment]
您好 监督训练刚开始mIOU就是100%是什么原因
