### ISSUE TITLE
监督训练过程

### ISSUE THREAD

**Issue by yyamx** [LiheYoung/ST-PlusPlus#33]
您好 我想问一下我的监督训练过程第一轮开始mIOU就是100% 损失为0的原因 还是说我的val有问题

**Comment by HuashengPang** [comment]
老师您好，请问我可以把数据集换成医学图像上的ACDC来在你的项目上运行吗？？谢谢

**Comment by LiheYoung** [comment]
@yyamx 你好，你使用的是Pasca VOC数据集吗？

**Comment by LiheYoung** [comment]
@HuashengPang 可以的，但需要进行一些数据读取的修改，因为目前我们的dataset是针对Pascal VOC和Cityscapes的。
