### ISSUE TITLE
训练过程中的报错

### ISSUE THREAD

**Issue by inscapeee** [LiheYoung/ST-PlusPlus#34]
老师您好，我想请问一下--unlabeled-id-path 应该怎样设置，如果按照readme.md的设置，代码会在Total stage 2/3: Pseudo labeling all unlabeled images过程中会终端训练并报错找不到VOC2012文件下缺少图片。在unlabeled.txt中无标签图像名称和标签名称一一对应，但数据集中并没有这些无标记图像的标签，不懂为什么这样设置，请老师为我解惑。

**Comment by LiheYoung** [comment]
你好，可能是由于你没有下载我们[这里](https://github.com/LiheYoung/ST-PlusPlus#dataset)提供的``Pascal SegmentationClass``. 当然，对于unlabeled data，我们只是会读取这些人工标注的mask，而不会在算法中使用这些标注。
