### ISSUE TITLE
数据集的文件放置

### ISSUE THREAD

**Issue by HuashengPang** [LiheYoung/ST-PlusPlus#35]
老师您好，请问这个数据集的文件结构怎么放置的??

**Comment by LiheYoung** [comment]
可以参考这个结构：https://github.com/LiheYoung/ST-PlusPlus#file-organization

**Comment by HuashengPang** [comment]
好的，感谢老师




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LiheYoung/ST-PlusPlus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月19日(星期天) 晚上11:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LiheYoung/ST-PlusPlus] 数据集的文件放置 (Issue #35)





 
可以参考这个结构：https://github.com/LiheYoung/ST-PlusPlus#file-organization
