### ISSUE TITLE
About the number of images in each epoch.

### ISSUE THREAD

**Issue by Haochen-Wang409** [LiheYoung/ST-PlusPlus#5]
Hi, Lihe. I'm a littble bit confused of the number of images in each epoch.

As you mentioned `over-sampler' in Algorithm 1.
![image](https://user-images.githubusercontent.com/62472073/131818952-102be709-7e57-4f35-b55a-7623519f357f.png)
Take the split 1464+9118 as example. Then, one epoch would contain 2*9118 images. Or, following previous definition, one epoch only contains 10582 images?

Thanks for your excellent work~

**Comment by LiheYoung** [comment]
Hi Haochen, 

In your case, one epoch contains *around* ``2x9118`` images. The exact number is ``9118 + ceil(9118 / 1464) x 1464``.

You may refer to this line that over-samples the labeled images:
https://github.com/LiheYoung/ST-PlusPlus/blob/ee7c9b2653647efc2b1d00919b40886fd09c1330/dataset/semi.py#L38-L39

**Comment by Haochen-Wang409** [comment]
Thanks for your patience! I appreciate it a lot.
