### ISSUE TITLE
Why the split of VOC has three different versions? And ST++ choosed which one to train on?

### ISSUE THREAD

**Issue by pascal1129** [LiheYoung/ST-PlusPlus#6]
https://github.com/LiheYoung/ST-PlusPlus/tree/master/dataset/splits/pascal/92/split_0

https://github.com/LiheYoung/ST-PlusPlus/tree/master/dataset/splits/pascal/92/split_1

https://github.com/LiheYoung/ST-PlusPlus/tree/master/dataset/splits/pascal/92/split_2

Three different versions of split, which exist at the same time, quite confused me.

**Comment by LiheYoung** [comment]
Hi, 

In the extremely scarce-data scheme, such as only 92 labeled images, different selections of labeled images will make a noticeable difference to the final result. Therefore, we provide three splits for the stability. You may run experiments on all of them and report the average performance.

Limited by time and computational resource, our experiments are mainly conducted on the first split (split_0).
