### ISSUE TITLE
About the batch_size

### ISSUE THREAD

**Issue by Haochen-Wang409** [LiheYoung/ST-PlusPlus#8]
Hi, sorry for disturbing you again.

In your paper, you said that the ```batch size``` is 16 for both VOC and Cityscapes with 2 and 4 V100 respectively.
I wonder whether 16 is the ```batch size``` for each V100 or is the ```total batch size``` (i.e., for VOC, the batch size for each V100 is 8 and 4 for Cityscapes)?

**Comment by LiheYoung** [comment]
Hi, 

The ``16`` is the total batch size.
