### ISSUE TITLE
A question about training epoch

### ISSUE THREAD

**Issue by chaochao42** [LiheYoung/ST-PlusPlus#9]
It seems that in "Supervised training on labeled images (SupOnly)" stage, you double the dataset when the number of images is less than 200. So in some setting as "92 labeled images", the actual training epoch is 160 rather than 80?
<img width="713" alt="wecom-temp-541d4d0afcfdd6eabc89c7de9c9a764c" src="https://user-images.githubusercontent.com/40266165/133732677-4eb6f32c-670d-4c3c-9e4b-cde6b7d93d35.png">

**Comment by LiheYoung** [comment]
You can understand in this way. 

However, one small difference is that we double the training images in EACH epoch and still validate 80 times, rather than 160 times.
